// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { DateVerificationEscrow$Type } from "./DateVerificationEscrow";
import { Staker$Type } from "./Staker";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DateVerificationEscrow"]: DateVerificationEscrow$Type;
    ["Staker"]: Staker$Type;
    ["contracts/contract.sol:DateVerificationEscrow"]: DateVerificationEscrow$Type;
    ["contracts/contract.sol:Staker"]: Staker$Type;
  }
}
