/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DateVerificationEscrow } from "./DateVerificationEscrow";
export * as factories from "./factories";
export { DateVerificationEscrow__factory } from "./factories/DateVerificationEscrow__factory";
